name: Deploy Flask App to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "."
          target: "/home/ubuntu/python_project"

      - name: Setup environment and run Flask on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Update packages and install Python & venv
            sudo apt update -y
            sudo apt install -y python3-pip python3-venv

            cd /home/ubuntu/python_project

            # Create virtual environment if it doesn't exist
            [ -d venv ] || python3 -m venv venv

            # Activate virtual environment
            source venv/bin/activate

            # Install Python dependencies inside venv
            pip install -r requirements.txt

            # Start Flask app in background
            nohup python3 app.py > app.log 2>&1 &
