name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e
          if [ ! -d "/home/ubuntu/python_project" ]; then
            cd /home/ubuntu
            git clone https://github.com/kishoreuppathala5283/python_project.git
            cd python_project
            python3 -m venv venv
          else
            cd /home/ubuntu/python_project
            git pull origin main --rebase || true
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          sudo systemctl restart flaskapp || echo "Service not created yet"
